package tech.icedlab.advagri.block;

public enum AdvAgriBlocksEnum {
    //MetalOre
    COPPER_ORE,
    ZINC_ORE,
    TIN_ORE,
    ALUMINUM_ORE,
    LEAD_ORE,
    SILVER_ORE,
    HIGH_CARBON_IRON_ORE,
    NICKEL_ORE,
    TUNGSTEN_ORE,
    TITANIUM_ORE,

    //WeatheredOre
    WEATHERED_COPPER_ORE,
    WEATHERED_ZINC_ORE,
    WEATHERED_TIN_ORE,
    WEATHERED_ALUMINUM_ORE,
    WEATHERED_LEAD_ORE,
    WEATHERED_SILVER_ORE,
    WEATHERED_HIGH_CARBON_IRON_ORE,
    WEATHERED_NICKEL_ORE,
    WEATHERED_TUNGSTEN_ORE,
    WEATHERED_TITANIUM_ORE,

    //Block
    COPPER_BLOCK,
    ZINC_BLOCK,
    TIN_BLOCK,
    BRONZE_BLOCK,
    ALUMINUM_BLOCK,
    LEAD_BLOCK,
    SILVER_BLOCK,
    STEEL_BLOCK,
    NICKEL_BLOCK,
    TUNGSTEN_BLOCK,
    TITANIUM_BLOCK,
    COPPER_CABLE,
    TIN_CABLE,
    SILVER_CABLE,
    GOLD_CABLE,

    //OtherOre
    PHOS_ORE,
    SULPHUR_ORE,
    NETHER_SULPHUR_ORE,
    BAMBOO_BLOCK,
    QUARRY,

    //Machine blocks
    MACHINE_SHELL,
    ADVANCED_CRAFTING_TABLE,
    FERMENT_TANK,
    BURNING_TANK,
    SUNSHINE_LIQUEFIES_MACHINE,
    SOLAR_HIGH_TEMPERATURE_ELECTROLYZE_MACHINE,
    CRUSHER,
    EXTRACTOR,
    CENTRIFUGE,
    ORE_WASHING_MACHINE,
    RESIN_EXTRACTOR,
}
