package tech.icedlab.advagri.item;

public enum AdvAgriToolsAndWeaponsEnum {
    COPPER_SHOVEL,
    COPPER_PICKAXE,
    COPPER_AXE,
    COPPER_HOE,
    COPPER_SWORD,

    ZINC_SHOVEL,
    ZINC_PICKAXE,
    ZINC_AXE,
    ZINC_HOE,
    ZINC_SWORD,

    TIN_SHOVEL,
    TIN_PICKAXE,
    TIN_AXE,
    TIN_HOE,
    TIN_SWORD,

    BRONZE_SHOVEL,
    BRONZE_PICKAXE,
    BRONZE_AXE,
    BRONZE_HOE,
    BRONZE_SWORD,

    ALUMINUM_SHOVEL,
    ALUMINUM_PICKAXE,
    ALUMINUM_AXE,
    ALUMINUM_HOE,
    ALUMINUM_SWORD,

    LEAD_SHOVEL,
    LEAD_PICKAXE,
    LEAD_AXE,
    LEAD_HOE,
    LEAD_SWORD,

    SILVER_SHOVEL,
    SILVER_PICKAXE,
    SILVER_AXE,
    SILVER_HOE,
    SILVER_SWORD,

    STEEL_SHOVEL,
    STEEL_PICKAXE,
    STEEL_AXE,
    STEEL_HOE,
    STEEL_SWORD,

    NICKEL_SHOVEL,
    NICKEL_PICKAXE,
    NICKEL_AXE,
    NICKEL_HOE,
    NICKEL_SWORD,


    TUNGSTEN_SHOVEL,
    TUNGSTEN_PICKAXE,
    TUNGSTEN_AXE,
    TUNGSTEN_HOE,
    TUNGSTEN_SWORD,

    TITANIUM_SHOVEL,
    TITANIUM_PICKAXE,
    TITANIUM_AXE,
    TITANIUM_HOE,
    TITANIUM_SWORD,

    BAMBOO_DRILL_ROD,

}
