package tech.icedlab.advagri.item;


public enum AdvAgriItemsEnum {
    COM_FERT,
    TUNG_OIL,
    POTASSIUM_SALT_POWDER,
    PLANT_ASH,

    BOTTLE_SMALL,
    BOTTLE_LARGE,

    SOLARIUM_BOTTLE_LARGE,
    SOLARIUM_BOTTLE_MEDIUM,
    SOLARIUM_BOTTLE_SMALL,

    BAMBOO_LEAVES,
    BAMBOO_SILK,
    BAMBOO_SILK_BOARD,
    BAMBOO_CHARCOAL,
    BAMBOO_SHOOT,

    PHOS,
    ZIRCON,
    SULFUR,

    CRUSHED_ALUMINUM_ORE,
    ALUMINUM_INGOT,
    ALUMINUM_POWDER,
    ALUMINUM_GEAR,
    ALUMINUM_PLATE,
    ALUMINUM_DISSOLVER,
    ALUMINUM_ROD,
    ALUMINUM_WIRE,

    CRUSHED_COPPER_ORE,
    COPPER_INGOT,
    COPPER_POWDER,
    COPPER_GEAR,
    COPPER_PLATE,
    COPPER_DISSOLVER,
    COPPER_ROD,
    COPPER_WIRE,

    CRUSHED_ZINC_ORE,
    ZINC_INGOT,
    ZINC_POWDER,
    ZINC_GEAR,
    ZINC_PLATE,
    ZINC_DISSOLVER,
    ZINC_ROD,
    ZINC_WIRE,

    CRUSHED_TIN_ORE,
    TIN_INGOT,
    TIN_POWDER,
    TIN_GEAR,
    TIN_PLATE,
    TIN_DISSOLVER,
    TIN_ROD,
    TIN_WIRE,

    BRONZE_SHARD,
    BRONZE_INGOT,
    BRONZE_POWDER,
    BRONZE_GEAR,
    BRONZE_PLATE,
    BRONZE_DISSOLVER,
    BRONZE_ROD,
    BRONZE_WIRE,

    CRUSHED_LEAD_ORE,
    LEAD_INGOT,
    LEAD_POWDER,
    LEAD_GEAR,
    LEAD_PLATE,
    LEAD_DISSOLVER,
    LEAD_ROD,
    LEAD_WIRE,

    CRUSHED_HIGH_CARBON_IRON_ORE,
    STEEL_INGOT,
    STEEL_POWDER,
    STEEL_GEAR,
    STEEL_PLATE,
    STEEL_ROD,

    CRUSHED_NICKEL_ORE,
    NICKEL_INGOT,
    NICKEL_POWDER,
    NICKEL_GEAR,
    NICKEL_PLATE,
    NICKEL_DISSOLVER,
    NICKEL_ROD,
    NICKEL_WIRE,

    CRUSHED_SILVER_ORE,
    SILVER_INGOT,
    SILVER_POWDER,
    SILVER_GEAR,
    SILVER_PLATE,
    SILVER_DISSOLVER,
    SILVER_ROD,
    SILVER_WIRE,

    CRUSHED_TUNGSTEN_ORE,
    TUNGSTEN_INGOT,
    TUNGSTEN_POWDER,
    TUNGSTEN_GEAR,
    TUNGSTEN_PLATE,
    TUNGSTEN_DISSOLVER,
    TUNGSTEN_ROD,
    TUNGSTEN_WIRE,

    CRUSHED_TITANIUM_ORE,
    TITANIUM_INGOT,
    TITANIUM_POWDER,
    TITANIUM_GEAR,
    TITANIUM_PLATE,
    TITANIUM_DISSOLVER,
    TITANIUM_ROD,
    TITANIUM_WIRE,

    IRON_SHARD,
    IRON_POWDER,
    IRON_GEAR,
    IRON_PLATE,
    IRON_DISSOLVER,
    CRUSHED_RAW_IRON,
    IRON_ROD,

    GOLD_SHARD,
    GOLD_POWDER,
    GOLD_GEAR,
    GOLD_PLATE,
    GOLD_DISSOLVER,
    CRUSHED_RAW_GOLD,
    GOLD_ROD,
    GOLD_FOIL,


    FIRECRACKERS,


    COPPER_CONDUCTOR_CORE,
    SILVER_CONDUCTOR_CORE,
    TITANIUM_CONDUCTOR_CORE,

    COPPER_COIL,
    ELECTRIC_MOTOR_SMALL,
    ELECTRIC_MOTOR_BIG,


    MINERAL_MUD,
    CORASE_ORE_POWDER,


    FORGING_HAMMER,
    BAMBOO_CHOPPER,
    WENCH,


    RICE_SEED_BAG,
    CHILI_SEED_BAG,
    CELERY_SEED_BAG,
    LETTUCE_SEED_BAG,
    STRAWBERRY_SEED_BAG,
    CORN_SEED_BAG,
    SWEET_POTATO_VINE,


    RICE_UNHUSKED,
    RICE,
    PLANT_STRAW,
    SWEET_POTATO,
    CHILI,
    CELERY,
    LETTUCE,
    STRAWBERRY,
    GARLIC,
    CHUFA,

    SOLAR_BERRY,

}
